name: Generate demo file

on: push

jobs:
    generate_gif:
        runs-on: ubuntu-latest
        steps:
            - name: Wait for github pages to finish building
            uses: lewagon/wait-on-check-action@v1.3.1
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                check_name: GitHub Pages
            
            - name: Website to file
            uses: actions/checkout@v3
            uses: PabloLec/website-to-gif@2.1.3
            with:
                url: https://ghostscyper.github.io/${{ github.repository }}/src/index.html
                file_name: demo.gif

            - name: Commit the file to the output branch
            uses: EndBug/add-and-commit@v7
            with:
                branch: output
                message: Generate demo file
                add: demo.gif

            - name: Push the output branch
            uses: ad-m/github-push-action@master
            with:
                branch: output
                github_token: ${{ secrets.GITHUB_TOKEN }}
                